//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adatbazis
{
    using System;
    using System.Collections.Generic;
    
    public partial class BikeAlkatreszek
    {
        public decimal ID { get; set; }
        public string TIPUS { get; set; }
        public Nullable<decimal> VAZ { get; set; }
        public Nullable<decimal> KEREK { get; set; }
        public Nullable<decimal> KORMANY { get; set; }
        public Nullable<decimal> MEREVVILLA { get; set; }
        public Nullable<decimal> BOWDEN { get; set; }
        public Nullable<decimal> PEDAL { get; set; }
        public Nullable<decimal> NYEREG { get; set; }
        public Nullable<decimal> TELESZKOP { get; set; }
    
        public virtual Bike Bike { get; set; }
    }
}
