//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adatbazis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kimutata
    {
        public decimal ID { get; set; }
        public string NEV { get; set; }
        public Nullable<decimal> MENNYISEG { get; set; }
    }
}
