//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adatbazis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TITAN_KEREKEntities : DbContext
    {
        public TITAN_KEREKEntities()
            : base("name=TITAN_KEREKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BiciklikRendelesre> BiciklikRendelesres { get; set; }
        public virtual DbSet<Bike> Bikes { get; set; }
        public virtual DbSet<BikeAlkatreszek> BikeAlkatreszeks { get; set; }
        public virtual DbSet<Felhasznalo> Felhasznaloes { get; set; }
        public virtual DbSet<Kimutata> Kimutatas { get; set; }
        public virtual DbSet<Raktar> Raktars { get; set; }
        public virtual DbSet<Rendelesek> Rendeleseks { get; set; }
        public virtual DbSet<Uzenetek> Uzeneteks { get; set; }
    }
}
